
cellsnp: "/research/groups/mackgrp/home/common/Software/miniconda3/envs/cellsnp/bin/cellsnp-lite"
vcfdb: "/research/groups/mackgrp/home/common/Software/1000G/hg38/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf.gz"

input_tsv: "samples.tsv"
output_base: "/research/groups/mackgrp/home/common/Analysis/Project_PrimaryRelapse/snatac/out_cellsnps"

threads: 25
memory: "128G"

minMAF: 0
minCOUNT: 2
